### PR TITLE
Fix: minOpen is true will drop a piece

### LINKED ISSUE #12121: visualMap - minOpen option breaks splitNumber and pieces
### Version
4.6.0

### Reproduction link
[https://jsfiddle.net/ue2h5z79/](https://jsfiddle.net/ue2h5z79/)

### Steps to reproduce
In the "options"->"visualMap" object change the "minOpen" proberty to "true".

### What is expected?
I expect a piece to be added to the pieces in the chart, meaning that it should have 6 pieces now. 5 for the range between min and max value and 1 for values lower min.

### What is actually happening?
The piece for lower than the min value is added, BUT suddenly the range between min and max value has one piece less and the last piece includes a bigger range than the others. It is still 5 pieces but I would expect 6.

If you change the "maxOpen" proberty to "true" it shows the expected behaviour, meaning it has now 6 pieces.

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

When minOpen is true, index shouldn't increase to 1

### Fixed issues

Close #12121

### Before: What was the problem?
Screen Shot 2020-02-14 at 20 45 30

### After: How is it fixed in this PR?

Screen Shot 2020-02-14 at 20 45 06

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [x] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by pissang** [comment]
LGTM

**Comment by pissang** [comment]
In this way, the `splitNumber` is not 6 instead of 5 . I'm not sure it's by design. @100pah Please have a look at this.

File: src/component/visualMap/PiecewiseModel.js [hunk 1]
```diff
@@ -402,7 +402,7 @@ var resetMethods = {
 
         if (thisOption.minOpen) {
             pieceList.push({
-                index: index++,
+                index: index,
```
Comment (100pah) [inline src/component/visualMap/PiecewiseModel.js]: Only remove `++` is not correct. Because after `++` removed, the first piece and the second piece has the same `index`.
That cause when click on the first piece, both the first piece and the second pieces are highlighted/downplayed.

Comment (100pah) [reply src/component/visualMap/PiecewiseModel.js]: Also consider
(1) @pissang mentioned: when the split number is `5`, the final pieces should better be `5`.
(2) The potential but that the `piece.index` forget to change after `reformIntervals(pieceList)` called.

I think the code to solve this issue could be:

```js
    splitNumber: function () {
        var thisOption = this.option;
        var pieceList = this._pieceList;
        var precision = Math.min(thisOption.precision, 20);
        var dataExtent = this.getExtent();
        var splitNumber = thisOption.splitNumber;
        splitNumber = Math.max(parseInt(splitNumber, 10), 1);
        thisOption.splitNumber = splitNumber;
+       var closedIntervalCount = splitNumber - (+thisOption.minOpen) - (+thisOption.maxOpen);

-       var splitStep = (dataExtent[1] - dataExtent[0]) / splitNumber;
+       var splitStep = (dataExtent[1] - dataExtent[0]) / closedIntervalCount;
        // Precision auto-adaption
        while (+splitStep.toFixed(precision) !== splitStep && precision < 5) {
            precision++;
        }
        thisOption.precision = precision;
        splitStep = +splitStep.toFixed(precision);

-       var index = 0;

        if (thisOption.minOpen) {
            pieceList.push({
-               index++,
                interval: [-Infinity, dataExtent[0]],
                close: [0, 0]
            });
        }

        for (
-           var curr = dataExtent[0], len = index + splitNumber;
-           index < len;
-           curr += splitStep
+           var index = 0, curr = dataExtent[0];
+           index < closedIntervalCount;
+           curr += splitStep, index++
        ) {
            var max = index === splitNumber - 1 ? dataExtent[1] : (curr + splitStep);

            pieceList.push({
-               index: index++,
                interval: [curr, max],
                close: [1, 1]
            });
        }

        if (thisOption.maxOpen) {
            pieceList.push({
-               index: index++,
                interval: [dataExtent[1], Infinity],
                close: [0, 0]
            });
        }

        reformIntervals(pieceList);

-       zrUtil.each(pieceList, function (piece) {
+       zrUtil.each(pieceList, function (piece, index) {
+           piece.index = index;
            piece.text = this.formatValueText(piece.interval);
        }, this);
    },

```

**Comment by susiwen8** [comment]
@pissang  @100pah  I have reservation on split number, clearly user wants to add a piece if they specify minOpen or maxOpen

> I expect a piece to be added to the pieces in the chart, meaning that it should have 6 pieces now. 5 for the range between min and max value and 1 for values lower min.

**Comment by 100pah** [comment]
@susiwen8 
>  I have reservation on split number, clearly user wants to add a piece if they specify minOpen or maxOpen

@pissang have mentioned me and think your suggestion is reasonable:
That is,
`finalPieceCount = userSpecifiedSplitNumber + (minOpen ? 1 : 0) + (maxOption ? 1 : 0)`
