### PR TITLE
fix(svg): svg doesn't support addHover; fix #11054

### LINKED ISSUE #11054: [Found in test: lines-stream-not-large.html] addHover not implemented with SVG
### Version
4.2.1

### Steps to reproduce
Run `test/lines-stream-not-large.html` with SVG. Hover on the map.

### What is expected?
No error.

### What is actually happening?
Error report in console:
`VM1257 echarts.js:17031 Uncaught TypeError: Cannot read property 'style' of undefined`.

This may caused by SVG do not have addHover function.

### PR DESCRIPTION
**Pull request by Ovilia**
fix #11054

### CODE REVIEW

File: src/util/graphic.js [hunk 1]
```diff
@@ -287,6 +287,12 @@ function singleEnterEmphasis(el) {
 
     if (useHoverLayer) {
```
Comment (100pah) [inline src/util/graphic.js]: Why not in SVG, useHoverLayer is always `false`.
It's a little confused that the behavior of calling addHover and getting a null

**Comment by pissang** [comment]
Agree with @100pah 

You can try ignore `useHoverLayer` flag when using SVG render and fall back to normal highlight approach, which will change the style of the original element.

It's more correct than return and do nothing . 

This solution also has  are some disadvantages, for example it will cause refresh and maybe block the user interaction when there are many elements. But I think developers should not use so much elements when using SVG renderer
