### PR TITLE
fix(map): map transform changed from geo coord to screen position; fix #11055

### LINKED ISSUE #11055: [Found in test: map.html] SVG shadow error
### Version
4.2.1

### Steps to reproduce
Run `test/map.html` with SVG. Hover on the map.

### What is expected?
The SVG shadow is the same as Canvas.

Canvas (correct): 
image

### What is actually happening?
The SVG shadow is not the same as Canvas.

SVG (wrong):
image

### PR DESCRIPTION
**Pull request by Ovilia**
The map transform has been changed from geo coordinate into screen position.
It solves the SVG shadow bug with #11055.

It computes the transform so that the path with map data is in screen coordinate rather than geo coordinate in the rendering stage.

Before: the path positions are in the geo coordinate.
After: the path positions are in the screen coordinate.

### CODE REVIEW

File: src/component/helper/MapDraw.js [hunk 1]
```diff
@@ -245,22 +237,33 @@ MapDraw.prototype = {
...
                 if (geometry.type !== 'polygon') {
                     return;
                 }
                 compoundPath.shape.paths.push(new graphic.Polygon({
                     segmentIgnoreThreshold: 1,
                     shape: {
-                        points: geometry.exterior
+                        points: zrUtil.map(geometry.exterior, function (point) {
+                            return transformPoint(point);
+                        })
```
Comment (pissang) [inline src/component/helper/MapDraw.js]: Use naive `for` loop may have better performance. Especially on the large GeoJSON.

**Comment by Ovilia** [comment]
I will check with #5429 tomorrow.

**Comment by Ovilia** [comment]
`test/geoScatter.html` show a demo of how to use pattern image in the map. See #5429.
