### PR TITLE
Fix dataview show NaN when user use dataset

### LINKED ISSUE #7533: 数据视图中显示NaN
### One-line summary [问题简述]
http://www.echartsjs.com/gallery/editor.html?c=dataset-simple0
官网示例，工具栏加上数据视图图标后，点击打开数字不显示，都显示NaN字样

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:应该是4.x
+ Browser version [浏览器类型和版本]:QQ浏览器10预览版，Chrome内核
+ OS Version [操作系统类型和版本]:Win10家庭版

### Expected behaviour [期望结果]
显示数字

### ECharts option [ECharts配置项]

```javascript
option = {

    legend: {},
    tooltip: {},
    dataset: {
        source: [
            ['product', '2015', '2016', '2017'],
            ['Matcha Latte', 43.3, 85.8, 93.7],
            ['Milk Tea', 83.1, 73.4, 55.1],
            ['Cheese Cocoa', 86.4, 65.2, 82.5],
            ['Walnut Brownie', 72.4, 53.9, 39.1]
        ]
    },
    xAxis: {type: 'category'},
    yAxis: {},
    // Declare several bar series, each will be mapped
    // to a column of dataset.source by default.
    series: [
        {type: 'bar'},
        {type: 'bar'},
        {type: 'bar'}
    ],
    "toolbox": {
    "feature": {
      "dataView": {}
    }}
}

```

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

When dataset is used, data view shows NaN.

### Fixed issues

Close #7533 

### Before: What was the problem?
Screen Shot 2019-12-14 at 12 45 09

### After: How is it fixed in this PR?
Screen Shot 2019-12-14 at 12 44 34

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [x] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/component/toolbox/feature/DataView.js [hunk 1]
```diff
@@ -93,7 +93,10 @@ function assembleSeriesWithCategoryAxis(series) {
         }));
         var columns = [categoryAxis.model.getCategories()];
         zrUtil.each(group.series, function (series) {
-            columns.push(series.getRawData().mapArray(valueAxisDim, function (val) {
+            // Using `series.name` as dimension when dataset is being used.
+            columns.push(series.getRawData().mapArray(series.dependentModels.dataset.length
+                ? series.name
+                : valueAxisDim, function (val) {
```
Comment (100pah) [inline src/component/toolbox/feature/DataView.js:99]: `series.name` happens to be the dimension name in this case but does not necessarily always be dimension name.
And I think the indent (`, function (val) { ... `) is not good.

I think a simple fix of the issue could be:
```js
var rawData = series.getRawData();
columns.push(rawData.mapArray(rawData.mapDimension(valueAxisDim), function (val) {
    return val;
}));
```
