### PR TITLE
Fix/axis pointer multi

### LINKED ISSUE #2869: 折线图且x轴type=time,tooltip为axis时,每个拐点前面一段显示的tip信息不正确
#### 问题简述 (One-line summary)
结果集只有两个值（1或2），设置x轴type=time,tooltip=axis,鼠标移动到拐点的前面一段范围，查看tooltip时，发现tooltip上的时间和值显示错误，显示成了拐点上的值和时间

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echarts3.0
+ 浏览器类型和版本 (Browser version):Chrome 46.0.2490.80 
+ 操作系统类型和版本 (OS Version):windows 7和iphone 6

#### 重现步骤 (Steps to reproduce)
1.鼠标移动到值为2的地方
2.查看tooltip显示

#### 期望结果 (Expected behaviour)
tooltip上显示正确的时间和值2

#### ECharts配置项 (ECharts option)

```javascript
function randomData(i) {
    now = new Date(+now + oneDay);
    var value = (i%4===0)?1:2;
    if(null !== preValue){
        data.push({
        name: now.toString(),
        value: [
            [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('-'),
            Math.round(preValue)
         ]
       });
    }
    
    preValue = value;
    return {
        name: now.toString(),
        value: [
            [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('-'),
            Math.round(value)
        ]
    }
}

var data = [];
var now = +new Date(1997, 9, 3);
var oneDay = 24 * 3600 * 1000;
var preValue = null;
for (var i = 0; i < 10; i++) {
    data.push(randomData(i));
}

option = {
    title: {
        text: '动态数据 + 时间坐标轴'
    },
    tooltip: {
        trigger: 'axis',
        formatter: function (params) {
            params = params[0];
            var date = new Date(params.name);
            return date.getDate() + '/' + (date.getMonth() + 1) + '/' + date.getFullYear() + ' : ' + params.value[1];
        },
        axisPointer: {
            animation: false
        }
    },
    xAxis: {
        type: 'time',
        splitLine: {
            show: false
        }
    },
    yAxis: {
        type: 'value',
        boundaryGap: [0, '100%'],
        splitLine: {
            show: false
        }
    },
    series: [{
        name: '模拟数据',
        type: 'line',
        showSymbol: false,
        hoverAnimation: false,
        
        data: data
    }]
};


```

#### 其他信息 (Other comments)

qq 20160321144008

### LINKED ISSUE #9829: tooltip x-axis has multi value
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

Tooltip has both left and right scale data when cursor is just between two scale  

### Expected Behavior
Only left data in tooltip

### Current Behavior
Both left and right data in tooltip.

effect

params

## Topics
- [ ] Legend
- [x] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

I read the indicesOfNearest in data/List.js and found the follow code 
```js
for (var i = 0, len = this.count(); i < len; i++) {
  var  diff  =  value  -  this.get(dim, i);
  var  dist  =  Math.abs(diff);
  if (diff <= maxDistance && dist <= minDist) {
    // For the case of two data are same on xAxis, which has sequence data.
    // Show the nearest index
    // https://github.com/ecomfe/echarts/issues/2869
    if (dist < minDist || diff >= 0 && minDiff < 0) {
      minDist = dist;
      minDiff = diff;
      nearestIndices.length  =  0;
    }
    nearestIndices.push(i);
  }
}
```
if the value is just between dim[i] and dim[i+1], then i and i+1 both push to nearestIndices

## Environment

- ECharts version；ECharts 版本: {4.1.0}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

### PR DESCRIPTION
**Pull request by 100pah**
fix: 
(1) Fix that tooltip shows multiple values around both sides of the pointer. Fix #9829. 
(2) Fix a probably typo (diff < maxDistance) introduced by https://github.com/apache/incubator-echarts/commit/4ef66e1d892485ced1dbfcf915135e7740bb7cc3
(3) Remove the previous logic that resolved #2869. Because currently if there are multiple values on the same axis tick, both of them will be found and displayed in tooltip by default. The related historical commits:
https://github.com/apache/incubator-echarts/commit/60d341f4ed9e33381099624962a8388eef8a9547  (fix #2869)
https://github.com/apache/incubator-echarts/commit/3426bd0e544b16f90a476cd36a79119c3570a63b  (support find multiple values on the same axis tick).

### CODE REVIEW

File: src/data/List.js [hunk 1]
```diff
@@ -1159,23 +1159,31 @@ listProto.indicesOfNearest = function (dim, value, maxDistance) {
...
-            // Show the nearest index
-            // https://github.com/ecomfe/echarts/issues/2869
-            if (dist < minDist || (diff >= 0 && minDiff < 0)) {
+        if (dist <= maxDistance) {
+            // When the `value` is at the middle of `this.get(dim, i)` and `this.get(dim, i+1)`,
+            // we'd better not push both of them to `nearestIndices`, otherwise it is easy to
+            // get more than one item in `nearestIndices` (more specifically, in `tooltip`).
+            // So we chose the one that `diff >= 0` in this csae.
+            if (dist < minDist
+                || (dist === minDist && diff >= 0 && minDiff < 0)
```
Comment (pissang) [inline src/data/List.js]: Is this same to `(dist === minDist && diff !== minDiff)` because `diff` is `dist` with sign

File: src/data/List.js [hunk 2]
```diff
@@ -1159,23 +1159,31 @@ listProto.indicesOfNearest = function (dim, value, maxDistance) {
...
+            ) {
                 minDist = dist;
                 minDiff = diff;
-                nearestIndices.length = 0;
+                nearestIndicesLen = 0;
+            }
+            if (diff === minDiff) {
```
Comment (pissang) [inline src/data/List.js]: I'm confused about this condition. `diff` should be always same with  `minDiff` if https://github.com/apache/incubator-echarts/blob/2eac3913216f4f9a462897a0da839a878d438dea/src/data/List.js#L1177 is executed.

File: src/data/List.js [hunk 3]
```diff
@@ -1159,23 +1159,31 @@ listProto.indicesOfNearest = function (dim, value, maxDistance) {
...
         var dist = Math.abs(diff);
-        if (diff <= maxDistance && dist <= minDist) {
-            // For the case of two data are same on xAxis, which has sequence data.
-            // Show the nearest index
-            // https://github.com/ecomfe/echarts/issues/2869
-            if (dist < minDist || (diff >= 0 && minDiff < 0)) {
+        if (dist <= maxDistance) {
+            // When the `value` is at the middle of `this.get(dim, i)` and `this.get(dim, i+1)`,
+            // we'd better not push both of them to `nearestIndices`, otherwise it is easy to
+            // get more than one item in `nearestIndices` (more specifically, in `tooltip`).
```
[the remark this answers is not in the document]
Comment (100pah) [reply src/data/List.js]: No. If there are more than one items on a axis ticks, we get more than one items.
If  itemN --- pointer ---- itemN+1  we got only itemN, but not both itemN and itemN+1.
But the comment need to be updated to make it more understandable.

File: src/data/List.js (hunk 1 above)
Comment (100pah) [reply src/data/List.js]: Only when the current `minDiff < 0` and `diff >= 0` we clear the previous records.
That means that we choose `diff >= 0` with higher priority than `diff <= 0`.

File: src/data/List.js (hunk 2 above)
Comment (100pah) [reply src/data/List.js]: The previous condition
```js
 if (dist < minDist
                || (dist === minDist && diff >= 0 && minDiff < 0) { ... }
```
is not always entered, as the previous comment described.

File: src/data/List.js [hunk 4]
```diff
@@ -1159,23 +1159,31 @@ listProto.indicesOfNearest = function (dim, value, maxDistance) {
...
+            if (dist < minDist
+                || (dist === minDist && diff >= 0 && minDiff < 0)
+            ) {
                 minDist = dist;
                 minDiff = diff;
-                nearestIndices.length = 0;
+                nearestIndicesLen = 0;
+            }
+            if (diff === minDiff) {
+                nearestIndices[nearestIndicesLen++] = i;
```
[the remark this answers is not in the document]
Comment (100pah) [reply src/data/List.js]: Just a little optimize to avoid always do `arr.length = 0; arr.push(i)`.
I think it's OK since many self managed length is used in ArrayBuffer in this file ?

[the remark this answers is not in the document]
Comment (pissang) [reply src/data/List.js]: Understand, didn't see the `nearestIndicesLen` will be reset to 0 in line https://github.com/apache/incubator-echarts/blob/2eac3913216f4f9a462897a0da839a878d438dea/src/data/List.js#L1178

File: src/data/List.js (hunk 2 above)
Comment (pissang) [reply src/data/List.js]: Can we get the following rule from these codes:

If the condition 
```js
dist < minDist || (dist === minDist && diff >= 0 && minDiff < 0)
```
is failed.

Then

1. `dist < minDist` => `Math.abs(diff) !== Math.abs(minDiff)` => `diff !== minDiff`
2. Or `diff >= 0 && minDiff < 0 ` => `diff !== minDiff`

Which means the `diff === minDiff` condition will always be failed.

Comment (100pah) [reply src/data/List.js]: `minDiff` and `minDist` will be modified if `dist < minDist || (dist === minDist && diff >= 0 && minDiff < 0)` is true. 

Take this test case for example:

```javascript
function core({diff, minDiff}) {
    console.log('---- minDiff:', minDiff, 'diff:', diff);
    var dist = Math.abs(diff);
    var minDist = Math.abs(minDiff);

    if (dist < minDist
        || (dist === minDist && diff >= 0 && minDiff < 0)
    ) {
        minDist = dist;
        minDiff = diff;
        nearestIndicesLen = 0;
        console.log('Clear previous');
    }
    if (diff === minDiff) {
        console.log('Add index');
    }
    else {
        console.log('Not add index');
    }
}


core({minDiff: 5, diff: -5})
core({minDiff: 5, diff: 5})
core({minDiff: -5, diff: 5})
core({minDiff: -5, diff: -5})
core({minDiff: 5, diff: 4})
core({minDiff: -5, diff: -4})
core({minDiff: 5, diff: 6})
core({minDiff: -5, diff: -6})
```

The result is:
```
---- minDiff: 5 diff: -5
 Not add index
---- minDiff: 5 diff: 5
 Add index
---- minDiff: -5 diff: 5
 Clear previous
 Add index
---- minDiff: -5 diff: -5
 Add index
---- minDiff: 5 diff: 4
 Clear previous
 Add index
---- minDiff: -5 diff: -4
 Clear previous
 Add index
---- minDiff: 5 diff: 6
 Not add index
---- minDiff: -5 diff: -6
 Not add index
```

Comment (pissang) [reply src/data/List.js]: The key difference between your `core` function and test case is 
```js
```
