### PR TITLE
fix(pie): add seriesId in pieselectchanged #9830

### LINKED ISSUE #9830: The returned value of pieselectchange missing attribute 'seriesId'
## General Questions

I tried to get Pie's seriesId with `pieselectchange` funciton while Pie's data is more than two, howerer, I suppose the result is 
```
{
    type: 'pieselected',
    // 系列 ID，可以在 option 中传入
    seriesId: string
    // 数据名称
    name: name,
    // 所有数据的选中状态表。
    selected: Object
}
```
but I get only
```
{
    type: 'pieselected',
    // 数据名称
    name: name,
    // 所有数据的选中状态表。
    selected: Object
}
```
And my series data is 
```
series: [
    {
          name: 'A',
          id: '123',
          center: [90, '101px'],
          radius: [0, '80px'],
          data: [
            { name: 'A1', value: 30 },
            { name: 'A2', value: 60 },
            { name: 'A3', value: 90 }
          ]
        },
        {
          name: 'B',
          id: '12',
          center: [298, '101px'],
          radius: [0, '80px'],
          data: [
            { name: 'A1', value: 30 },
            { name: 'A2', value: 60 },
            { name: 'A3', value: 90 }
          ]
        }
]
```

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [x] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

The result of  `pieselectchange` function missing `seriesId` params

### Expected Behavior

As document's result
```
{
    type: 'pieselected',
    // 系列 ID，可以在 option 中传入
    seriesId: string
    // 数据名称
    name: name,
    // 所有数据的选中状态表。
    selected: Object
}
```

### Current Behavior

Missing `seriesId`
{
    type: 'pieselected',
    // 数据名称
    name: name,
    // 所有数据的选中状态表。
    selected: Object
}

## Environment
Vue + vue-echarts + echarts

- ECharts version；ECharts 版本: { 4.x }

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

### LINKED ISSUE #9839: china.js map show question
image

### PR DESCRIPTION
**Pull request by Ovilia**
Add `seriesId` field in `pieselectchanged` event.
Fix #9830 .

### CODE REVIEW

File: src/action/createDataSelectAction.js [hunk 1]
```diff
@@ -50,7 +50,8 @@ export default function (seriesType, actionInfos) {
             );
             return {
                 name: payload.name,
-                selected: selected
+                selected: selected,
+                seriesId: payload.seriesId
```
Comment (100pah) [inline src/action/createDataSelectAction.js]: `payload` probably has no `seriesId`, and the action probably effect multiple series.

```js
dispatchAction({name: 'xxx'}); // Probably effect multiple series
dispatchAction({seriesName: 'xxx'}); // Probably effect multiple series
```

I think we'd better discuss more about the further enhancement of properties of events, which currently is not good enough. Some properties are missing.
And also we should consider that some common properties (like `seriesId` `seriesIndex` `componentIndex` `name`) should be consistent as far as possible.

Comment (100pah) [reply src/action/createDataSelectAction.js]: I have checked it again and I think this fix is correct. 
It can resolve the issue without negative effect to other cases.
The other cases can be discussed future.
