### PR TITLE
Fix #10910

### LINKED ISSUE #10910: itemStyle中color使用回调函数时，线条颜色不发生变化，只有节点颜色发生变化
### Version
4.2.1-rc1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xSatSVYKMck&v=1](https://gallery.echartsjs.com/editor.html?c=xSatSVYKMck&v=1)

### Steps to reproduce
无需操作，打开链接后已显示出bug

### What is expected?
当itemStyle的color使用回调函数时，线条颜色也能产生相应变化

### What is actually happening?
当itemStyle的color使用回调函数时，线条颜色不能产生相应变化

---
当itemStyle的color使用固定颜色（例如：'#ABCDEF'）时，线条颜色既然能变化为该颜色。<br />
那么itemStyle的color使用回调函数时为何不能改变线条颜色呢？我认为这并不合理。<br/>
而且这个与文档描述不符。

> 注： 修改 lineStyle 中的颜色不会影响图例颜色，如果需要图例颜色和折线图颜色一致，需修改 itemStyle.color，线条颜色默认也会取改颜色。

### PR DESCRIPTION
**Pull request by susiwen8**
Close #10910

### CODE REVIEW

**Comment by pissang** [comment]
Thanks @susiwen8 . Can you provide test cases?

**Comment by susiwen8** [comment]
@pissang I will add it this weekend

**Comment by susiwen8** [comment]
Test case has added.

File: src/chart/line/LineView.js [hunk 1]
```diff
@@ -453,6 +453,12 @@ export default ChartView.extend({
         }
 
         var visualColor = getVisualGradient(data, coordSys) || data.getVisual('color');
+        if (typeof visualColor === 'function') {
+            var color = visualColor;
+            data.each(function (idx) {
+                visualColor = color(seriesModel.getDataParams(idx));
+            });
```
Comment (pissang) [inline src/chart/line/LineView.js]: We don't have to iterate all the data to get a color here.

I think there are two solutions: 

+ use the first or last data for this callback and get one color value.
+ Or pick some of the data and get a gradient color.

From my perspective, gradient color is better, but the main concern is SVG or Canvas may have an issue with too many color stops on the gradient. About this, perhaps we can pick at most 10 of the data to get the gradient.

BTW: Personally I prefer using `colorCallback` over `color` on the variable name because it's more specific.

File: src/chart/line/LineView.js [hunk 2]
```diff
@@ -453,6 +453,9 @@ export default ChartView.extend({
         }
 
         var visualColor = getVisualGradient(data, coordSys) || data.getVisual('color');
+        if (typeof visualColor === 'function') {
+            visualColor = visualColor(seriesModel.getDataParams(0)) || '#000000';
+        }
```
Comment (100pah) [inline src/chart/line/LineView.js]: Use `seriesModel.getDataParams(0)` will cause that line color will be changed when using `dataZoom`.
Check this example please:
```js
            colors = ['red', 'blue', 'yellow', 'green'];
            option = {
                xAxis: {},
                yAxis: {},
                dataZoom: {},
                series: {
                    type: 'line',
                    itemStyle: {
                        color: function (params) {
                            return colors[params.dataIndex];
                        }
                    },
                    data: [[11, 22], [33, 44], [22, 33]]
                }
            };
```

I suggest that if the `itemStyle.color` is a `function`, we use the default color for line.
If line needs be colored, use `lineStyle.color` in this case.
By convention, the data.getVisual('color') should not be a function in the view stage.
The function should be processed in the visual stage.
I thinks we probably change the code here:
<https://github.com/apache/incubator-echarts/blob/0ebdeaf42d8a8e3830c160fa9cd27bcc434ce502/src/visual/seriesColor.js#L35>

If the color is a function, we still use the palette color. @pissang 
Or, to avoid some potential issue, save the original palette in another filed and use it in `LineView`.
