### PR TITLE
Fix: make `contentToOption` totally optional

### LINKED ISSUE #13031: toolbox optionToContent 自定义 dataView，点刷新，optionToContent回调中拿到的series数据遗失
### Version
4.8.0

### Steps to reproduce
1、在ECharts 的示例代码 [https://echarts.apache.org/examples/zh/editor.html?c=line-marker](https://echarts.apache.org/examples/zh/editor.html?c=line-marker)，填入下面代码（optionToContent为官网文档中的）
```js
option = {
    title: {
        text: '未来一周气温变化',
        subtext: '纯属虚构'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data: ['最高气温', '最低气温']
    },
    toolbox: {
        show: true,
        feature: {
            dataZoom: {
                yAxisIndex: 'none'
            },
            dataView: {
                readOnly: false,
                optionToContent: function(opt) {
                    console.log(opt)
                    var axisData = opt.xAxis[0].data;
                    var series = opt.series;
                    var table = '<table style="width:100%;text-align:center"><tbody><tr>' +
                        '<td>时间</td>' +
                        '<td>' + series[0].name + '</td>' +
                        '<td>' + series[1].name + '</td>' +
                        '</tr>';
                    for (var i = 0, l = axisData.length; i < l; i++) {
                        table += '<tr>' +
                            '<td>' + axisData[i] + '</td>' +
                            '<td>' + series[0].data[i] + '</td>' +
                            '<td>' + series[1].data[i] + '</td>' +
                            '</tr>';
                    }
                    table += '</tbody></table>';
                    return table;
                }

            },
            magicType: {
                type: ['line', 'bar']
            },
            restore: {},
            saveAsImage: {}
        }
    },
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
    },
    yAxis: {
        type: 'value',
        axisLabel: {
            formatter: '{value} °C'
        }
    },
    series: [{
            name: '最高气温',
            type: 'line',
            data: [11, 11, 15, 13, 12, 13, 10],
            markPoint: {
                data: [{
                        type: 'max',
                        name: '最大值'
                    },
                    {
                        type: 'min',
                        name: '最小值'
                    }
                ]
            },
            markLine: {
                data: [{
                    type: 'average',
                    name: '平均值'
                }]
            }
        },
        {
            name: '最低气温',
            type: 'line',
            data: [1, -2, 2, 5, 3, 2, 0],
            markPoint: {
                data: [{
                    name: '周最低',
                    value: -2,
                    xAxis: 1,
                    yAxis: -1.5
                }]
            },
            markLine: {
                data: [{
                        type: 'average',
                        name: '平均值'
                    },
                    [{
                        symbol: 'none',
                        x: '90%',
                        yAxis: 'max'
                    }, {
                        symbol: 'circle',
                        label: {
                            position: 'start',
                            formatter: '最大值'
                        },
                        type: 'max',
                        name: '最高点'
                    }]
                ]
            }
        }
    ]
};
```
2、点击图表上方“数据视图”图标，切换数据视图；
3、点击数据视图下方“刷新”按钮；
4、（问题出现）会到折线图视图，但此时只有一条曲线，曲线图少了一个系列；
5、（问题出现）若此时再点击切换到数据视图，可发现上面自定义数据视图table第二列数据全为undefined；

### What is expected?
自定义视图，和默认的 textarea 一样，点击刷新后会到图表视图，数据不发生错误，或者可隐藏刷新按钮

### What is actually happening?
使用optionToContent 自定义 dataView，点击刷新按钮后，数据出现遗失，且底部按钮无法隐藏，缺少回调函数

### PR DESCRIPTION
**Pull request by easonyq**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fix #13031 and #13086 

### Fixed issues

#13031 has described such a situation that user has provided `optionToContent` function while has not provided the corresponding `contentToOption` function.
If we think echarts should also work well in this situation, we need to make `contentToOption` function totally optional. (In other words, if user hasn't provided it, bugs like missing series data or showing a list of `undefined` should not happen.)

### Before: What was the problem?

If user provide `optionToContent` function but has not provided `contentToOption` function, press 'refresh' will lose data and make a list of `undefined` displayed.

### After: How is it fixed in this PR?

Even user has not provided `contentToOption` function, by pressing 'refresh' button also works well.

### Are there any API changes?

- [ ] The API has been changed.

No

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [x] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by easonyq** [comment]
In #13086 @pissang has raised an issue. He says that PR will make option not refreshed if user didn't provide `optionToContent` or `contentToOption` function and changed the default text area. This PR also fix that bug.

The key point here is:

1. If user has provided `optionToContent` function but missed `contentToOption` function, the system tried to parse the content in **textarea**. But actually **textarea is not appended to the document** in this case. So the content we need to parse is a user-provided HTML what `optionToContent` returned, rather than the default **textarea**.
2. Futhermore, if user provided a complicated HTML structure (such as a **table** described in #13031), it is difficult (or saying impossible) for us to parse it and get the right data we want.
3. By contrast, let's image the opposite situation that user has provided `contentToOption` function but missed `optionToContent` function. In this case, the default textarea will show but the parsing function is overwritten by user, which is totally unnecessary.
3. Given these facts, in my opinion user should still use `optionToContent` along with `contentToOption` **together**. Thus this PR gives warning when user missed one of these two. If he did, a warning message will be shown and all data will remain the same.

File: src/component/toolbox/feature/DataView.ts [hunk 1]
```diff
@@ -371,6 +371,13 @@ class DataView extends ToolboxFeature<ToolboxDataViewFeatureOption> {
         addEventListener(closeButton, 'click', close);
 
         addEventListener(refreshButton, 'click', function () {
+            if ((typeof contentToOption === 'undefined' && typeof optionToContent !== 'undefined') ||
+                (typeof contentToOption !== 'undefined' && typeof optionToContent === 'undefined')) {
```
Comment (pissang) [inline src/component/toolbox/feature/DataView.ts:375]: It will be better to use `null` check here

```
if (contentToOption == null ...) {}
```

File: src/component/toolbox/feature/DataView.ts [hunk 2]
```diff
@@ -371,6 +371,13 @@ class DataView extends ToolboxFeature<ToolboxDataViewFeatureOption> {
...
+                console.warn('It seems you have just provided one of `contentToOption` and `optionToContent` functions but missed the other one. Data change is ignored.')
+                close();
```
Comment (pissang) [inline src/component/toolbox/feature/DataView.ts:377]: Usually warn is only displayed in dev mode.

So a __DEV__ condition should be wrapped here.
```ts
if (__DEV__) {
  console.warn('....');
}
```

**Comment by pissang** [comment]
Hi @easonyq, thanks for the detailed explanation. I think the scenario you described is complete enough.

**Comment by easonyq** [comment]
Thanks for @pissang 's review. I've applied another patch.

**Review by pissang — APPROVED** [review]
