### PR TITLE
fix(pie): pie series render incorrectly after editing its data in DataView. close #12560.

### LINKED ISSUE #12560: Dataview 编辑数据之后重新渲染出错
### Version
4.3.0

### Steps to reproduce
点击数据视图删除某一行（如删除“美国	15276”）之后，重新绘制的pie chart把最后一行的name（即“其他”）删除了，“美国”还在，所有的数据也都错乱了（国家与数值没有对应），

### What is expected?
在删除某一行之后，重新绘制图形，如 删除“美国	15276”这一行之后，饼图中不出现美国。

### What is actually happening?
删除“美国	15276”这一行数据之后，只是删除了15276这个数据，但美国还在，而且其他国家的数据已经错乱了。

---
// my Code

var data = [{"name": "美国", "value": 15276.0}, {"name": "英国", "value": 4855.0}, {"name": "法国", "value": 3291.0}, {"name": "意大利", "value": 3157.0}, {"name": "西班牙", "value": 2859.0}, {"name": "巴西", "value": 1662.0}, {"name": "其他", "value": 5152.0}];
let name = "各国累计死亡人数"; 

option = {
	toolbox: {
		feature: {
		    dataView:{
		      readOnly: false  
		    },
		    restore:{},
			saveAsImage: {
				name: name
			}
		}
	},

	tooltip: {
		trigger: 'item',
		formatter: '{a} <br/>{b} : {c} ({d}%)'
	},
	series: [{
		name: name,
		type: 'pie',
		data: data,
		radius: '50%',
		clockwise: false, // 逆时针排序
		label: {
			formatter: "{b} : {num|{c}} | {rate|{d}%}",
			color: "black",
			fontSize: 20,
			rich: {
				num: {
					fontSize: 22,
					fontWeight: 'bold',
					color: "black"
				},
				rate: {
					fontSize: 22,
					fontWeight: 'bold',
					color: "black"
				},
				symbol: {
					fontSize: 22,
					color: "black"
				}
			}
		},
		emphasis: {
			itemStyle: {
				shadowBlur: 10,
				shadowOffsetX: 0,
				shadowColor: 'rgba(0, 0, 0, 0.5)'
			}
		}
	}]
};

### PR DESCRIPTION
**Pull request by plainheart**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

- 1. Fixes the issue #12560.
- 2. Fixes the bug that pie series will be rendered incorrectly when a user forgets to delete `\n` or retained some spaces in `DataView`.

### Fixed issues

Close #12560

### Code to Reproduce: 

- case 1. Click the `DataView` tool at the top-right cornor, and delete the first line `USA`.
- case 2. Delete the last line (but don't remove `\n` or  just retain some spaces).

### Before: 

image

image

### After: 

image

image

### Related test cases or examples to use the new APIs

Refer to `test/pie-dataView.html`

### CODE REVIEW

File: src/component/toolbox/feature/DataView.js [hunk 1]
```diff
@@ -426,13 +432,17 @@ function tryMergeDataOption(newData, originalData) {
     return zrUtil.map(newData, function (newVal, idx) {
         var original = originalData && originalData[idx];
         if (zrUtil.isObject(original) && !zrUtil.isArray(original)) {
-            if (zrUtil.isObject(newVal) && !zrUtil.isArray(newVal)) {
-                newVal = newVal.value;
+            var _newVal;
+            if (zrUtil.isArray(newVal) || zrUtil.isObject(newVal)) {
```
Comment (Ovilia) [inline src/component/toolbox/feature/DataView.js:436]: Thanks for your contribution.

Could you explain the change here?

And please do not use `_` in variable names.

Comment (plainheart) [reply src/component/toolbox/feature/DataView.js:436]: Thanks for your review and sorry for the wrong variable name defined before.

The reason for making these changes is to ensure more compatibility at first.

For the case: **Delete any data item in any line in GridView**

In original logic context, it only handles the change of `value` but does not handle the change of `name`. Therefore, after any data item line is deleted, final merged result will ignore `name`.

An example:
**original data items:**
```js
[
    { name:  'USA', value: 15276 },
    { name:  'UK', value: 4855 }
]
```

**the first in original data items** 
`{ name: 'USA', value: 15276 }`

**the first data item after the old first data item was deleted(the second became the first)**
`{  name:  "UK", value: 4855  }`

After `tryMergeDataOption`, data items became
`[ { name: 'USA', value: 4855 } ]`

The result above is not obviously expected.
Both `name` and `value` of each data item should be handled and merged well.

By now, I think there should be some changes here.
```js
function tryMergeDataOption(newData, originalData) {
    return zrUtil.map(newData, function (newVal, idx) {
        var original = originalData && originalData[idx];
        if (zrUtil.isObject(original) && !zrUtil.isArray(original)) {
            var newValIsObject = zrUtil.isObject(newVal) && !zrUtil.isArray(newVal);
            if (!newValIsObject) {
                newVal = {
                    value: newVal
                };
            }
            if (original.name != null && newVal.name == null) {
                // original data has name but new data has no name
                delete original.name;
            }
            // Original data has option
            return zrUtil.defaults(newVal, original);
        }
        else {
            return newVal;
        }
    });
}
```

Finally, I found another bug that it will occur after editing the series name in DataView.

image

File: src/component/toolbox/feature/DataView.js [hunk 2]
```diff
@@ -426,13 +432,18 @@ function tryMergeDataOption(newData, originalData) {
...
+            if (!newValIsObject) {
+                newVal = {
+                    value: newVal
+                };
+            }
+            // original data has name but new data has no name
+            if (original.name != null && newVal.name == null) {
+                delete original.name;
             }
             // Original data has option
```
Comment (pissang) [inline src/component/toolbox/feature/DataView.js:445]: Should not modify the original data. It's better to delete the name in newVal after `defaults`

Comment (plainheart) [reply src/component/toolbox/feature/DataView.js:443]: Yes, I missed it before. I've tweaked this logic, please help review, thank you.
