### PR TITLE
fix(pie): label not show when animation is disabled. fix #12110

### LINKED ISSUE #12110: Pie chart label not shown when animation is disabled
### Version
4.6.0

### Reproduction link
[https://jsfiddle.net/cLa5db8n/](https://jsfiddle.net/cLa5db8n/)

### Steps to reproduce
Define a basic pie chart and set `animation` to `false`.

### What is expected?
Labels should be displayed on mouse hover.

### What is actually happening?
Labels are not displayed. If I enable animation, then labels are displayed normally.

---
This issue started with 4.3.0 and happens to this day. v4.2.1 [was fine](https://jsfiddle.net/cLa5db8n/1/).

### PR DESCRIPTION
**Pull request by Ovilia**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Hover style is not used if pie animation is set to be false. 

### Fixed issues

- #12110: label not show when animation is disabled

### Before: What was the problem?

Test `test/pie-animation.html`. Label is not shown when hover on the pie.

### After: How is it fixed in this PR?

```
labelLine.ignore = labelLine.hoverIgnore;
labelText.ignore = labelText.hoverIgnore;
```

`labelLine.ignore` and `labelText.ignore` should be changed into `hoverIgnore`, even if without animation.

Note that a user may set `animation` to be true while `hoverAnimation` to be false for a pie chart to have the transition animation at initiation. So checking both `itemModel.get('hoverAnimation') && seriesModel.isAnimationEnabled()` in https://github.com/apache/incubator-echarts/commit/9847233b23a4d5bf65b01ebfb7d5547edb0e11cb#diff-19529e7aaddb5ad8b1b45417c96c8e00R184 does not update the animation states for transition animation.

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

`test/pie-animation.html` and a visual test about it.

### Merging options

- [x] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/chart/pie/PieView.js [hunk 1]
```diff
@@ -180,31 +180,36 @@ piePieceProto.updateData = function (data, idx, firstCreate) {
     var withAnimation = !firstCreate && animationTypeUpdate === 'transition';
     this._updateLabel(data, idx, withAnimation);
 
-    this.highDownOnUpdate = (itemModel.get('hoverAnimation') && seriesModel.isAnimationEnabled())
+    this.highDownOnUpdate = !seriesModel.get('silent')
         ? function (fromState, toState) {
+            const hasAnimation = seriesModel.isAnimationEnabled();
             if (toState === 'emphasis') {
```
Comment (pissang) [inline src/chart/pie/PieView.js:186]: Needs to check `hoverAnimation` configuration here.
