### PR TITLE
fix(line): overflow symbols should render if clip is false #11549

### LINKED ISSUE #11549: Symbols don't render right in clip mode
### Version
4.4.0

### Reproduction link
[https://jsfiddle.net/qraz7vxu/](https://jsfiddle.net/qraz7vxu/)

### Steps to reproduce
```
option = {
  grid: {
    top: 130,
    bottom: 80
  },
  dataZoom: [{
      type: 'slider',
      show: true
    },
    {
      type: 'inside'
    }
  ],
  xAxis: {
    type: 'category',
    name: 'x',
    splitLine: {
      show: false
    },
    data: ['1', '2', '3', '4', '5', '6', '7', '9', '9'],
    axisPointer: {
      show: 'true'
    },
  },
  yAxis: {
    name: 'y',
    max: 20
  },
  tooltip: {
    trigger: 'item'
  },
  series: [{
    name: 'B',
    type: 'line',
    clip: false,
    data: [1, 2, 4, 8, 16, 32, 64, 128, 256]
  }]
};
```

### What is expected?
Symbol outside clip area should be rendered.

### What is actually happening?
Symbol outside clip area didn't render.
image

I found it while fix #11360 in #11548 .

### PR DESCRIPTION
**Pull request by SnailSword**
fix #11549.

before:
image

after:
image

### CODE REVIEW

File: src/chart/line/LineView.js [hunk 1]
```diff
@@ -354,7 +354,7 @@ export default ChartView.extend({
         // FIXME step not support polar
         var step = !isCoordSysPolar && seriesModel.get('step');
         var clipShapeForSymbol;
-        if (coordSys && coordSys.getArea) {
+        if (coordSys && coordSys.getArea && seriesModel.get('clip')) {
```
Comment (pissang) [inline src/chart/line/LineView.js]: It's more robust to use `seriesModel.get('clip', true)`.

In this way it won't get the `clip` property in the root `option` if it is not exists in `series`.

**Comment by pissang** [comment]
Thanks a lot! I've planned it in this version.
