### PR TITLE
fix: #12812

### LINKED ISSUE #12812: tooltip position after resize or rotate window
### Version
4.0.4

### Steps to reproduce
1- display echart tooltip exemple: https://echarts.apache.org/examples/en/editor.html?c=line-tooltip-touch

2- add option 'alwaysShowContent: true' for tooltip

3- click on the chart for display tooltip

4- change window size or rotation

### What is expected?
selected point (line and tooltip) represent always the same part of the chart

### What is actually happening?
the tooltip move, not corresponding to the selected point position

### PR DESCRIPTION
**Pull request by liulinboyi**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

when alwaysShowContent is true change or rotation window size and restore will hide tooltip

### Fixed issues
Close #12812

### Before: What was the problem?

1- display echart tooltip exemple: https://echarts.apache.org/examples/en/editor.html?c=line-tooltip-touch

2- add option 'alwaysShowContent: true' for tooltip

3- click on the chart for display tooltip

4- change window size or rotation

the tooltip move, not corresponding to the selected point position

### After: How is it fixed in this PR?

when alwaysShowContent is true change or rotation window size and restore will hide tooltip

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

File: src/echarts.js [hunk 1]
```diff
@@ -1142,8 +1142,22 @@ echartsProto.resize = function (opts) {
...
     triggerUpdatedEvent.call(this, silent);
+
+    hideTooltip.call(this);
 };
 
+/**
+ * when alwaysShowContent is true change or rotation window size and restore will hide tooltip
+ */
+function hideTooltip() {
+    const tooltips = this._componentsViews.filter(item => item.__model.mainType === 'tooltip');
```
Comment (susiwen8) [inline src/echarts.js:1153]: Please use ES3, so `const` and `filter` are not allowed to be used in this project
https://echarts.apache.org/zh/coding-standard.html#language-features

Comment (susiwen8) [inline src/echarts.js:1153]: Also, any property started by '_' are private, so we shouldn't directly manipulate it

Comment (liulinboyi) [reply src/echarts.js]: Currently I have no other way to hide tooltip in resie.

Comment (liulinboyi) [reply src/echarts.js]: > Also, any property started by '_' are private, so we shouldn't directly manipulate it

Currently I have no other way to hide tooltip in resie

**Comment by plainheart** [comment]
Why hide tooltip rather than relocate it to the proper coordinate?
And I think doing it here is a bit inappropriate.

**Comment by liulinboyi** [comment]
> Why hide tooltip rather than relocate it to the proper coordinate?
> And I think doing it here is a bit inappropriate.

Let me have a try.

**Comment by liulinboyi** [comment]
> Why hide tooltip rather than relocate it to the proper coordinate?
> And I think doing it here is a bit inappropriate.

@plainheart The effect is as follows，Please help review, thanks!
move

File: src/echarts.js [hunk 2]
```diff
@@ -1142,8 +1143,26 @@ echartsProto.resize = function (opts) {
     flushPendingActions.call(this, silent);
 
     triggerUpdatedEvent.call(this, silent);
+
+    moveTooltip.call(this);
```
Comment (plainheart) [inline src/echarts.js:1147]: Still not sure whether it is proper to handle tooltip relocation here, maybe it's better to move these logic to `TooltipView`?

File: src/echarts.js [hunk 3]
```diff
@@ -1142,8 +1143,26 @@ echartsProto.resize = function (opts) {
...
+ */
+function moveTooltip() {
+    var tooltips = filter(this._componentsViews, function (item) {
+        return item.__model.mainType === 'tooltip';
+    });
+    each(tooltips, function (tooltip) {
+        var realLeft = tooltip._tooltipContent._styleCoord[2] * this._zr.getWidth();
+        var realRight = tooltip._tooltipContent._styleCoord[1];
+        var ratio = tooltip._tooltipContent._styleCoord[2];
+        tooltip._tooltipContent.moveTo(realLeft, realRight, ratio);
```
Comment (plainheart) [inline src/echarts.js]: I can't find the usage of the parameter `ratio`, did I miss something?

Comment (liulinboyi) [reply src/echarts.js]: > I can't find the usage of the parameter `ratio`, did I miss something?

The code has just been updated to remove this parameter.

File: src/echarts.js (hunk 2 above)
Comment (liulinboyi) [reply src/echarts.js:1147]: > Still not sure whether it is proper to handle tooltip relocation here, maybe it's better to move these logic to `TooltipView`?

Let me have a try.

**Comment by liulinboyi** [comment]
@plainheart All the problems are solved, Please help review, thanks!

File: src/component/tooltip/TooltipContent.js [hunk 4]
```diff
@@ -250,11 +253,23 @@ TooltipContent.prototype = {
...
+    /**
+     * when alwaysShowContent is true change or rotation window size and restore will move tooltip
+     * @private
+     */
+    _moveTooltip: function() {
+        var ratio = this._styleCoord[2]; // The ratio of left to width
+        var realLeft = ratio * this._zr.getWidth();
+        var realRight = this._styleCoord[1];
+        this.moveTo(realLeft, realRight);
+    },
```
Comment (plainheart) [inline src/component/tooltip/TooltipContent.js:271]: The height ratio also should be handled.
```suggestion
    _moveTooltip: function() {
        var ratioX = this._styleCoord[2];
        var ratioY = this._styleCoord[3];
        var realX = ratioX * this._zr.getWidth();
        var realY = ratioY * this._zr.getHeight();
        this.moveTo(realX, realY);
    },
```

File: src/component/tooltip/TooltipContent.js [hunk 5]
```diff
@@ -169,7 +172,7 @@ function TooltipContent(container, api, opt) {
     var zr = this._zr = api.getZr();
     var appendToBody = this._appendToBody = opt && opt.appendToBody;
 
-    this._styleCoord = [0, 0];
+    this._styleCoord = [0, 0, 0];
```
Comment (plainheart) [inline src/component/tooltip/TooltipContent.js:175]: Looks good. But it still needs a ratio of `height` to handle the height change and relocate the tooltip.
So `_styleCoord` should be `[0, 0, 0, 0]`.

File: src/component/tooltip/TooltipContent.js [hunk 6]
```diff
@@ -131,18 +131,21 @@ function makeStyleCoord(out, zr, appendToBody, zrX, zrY) {
...
         // xy should be based on canvas root. But tooltipContent is
         // the sibling of canvas root. So padding of ec container
         // should be considered here.
         var viewportRootOffset = zrPainter && zrPainter.getViewportRootOffset();
         if (viewportRootOffset) {
             out[0] += viewportRootOffset.offsetLeft;
             out[1] += viewportRootOffset.offsetTop;
+            out[2] = out[0] / zr.getWidth(); // The ratio of left to width
         }
     }
```
Comment (plainheart) [inline src/component/tooltip/TooltipContent.js:150]: We can move these logic to the very bottom of `makeStyleCoord` .
```js
out[2] = out[0] / zr.getWidth();
out[3] = out[1] / zr.getHeight();
```

File: src/component/tooltip/TooltipContent.js [hunk 7]
```diff
@@ -250,11 +253,23 @@ TooltipContent.prototype = {
         if (domStyle.position !== 'absolute' && stl.position !== 'absolute') {
             domStyle.position = 'relative';
         }
+        this._moveTooltip()
```
Comment (plainheart) [inline src/component/tooltip/TooltipContent.js:256]: Maybe should add a judgement about whether `alwaysShowContent` is `true`
`TooltipView.js`([Line 112](https://github.com/apache/incubator-echarts/blob/master/src/component/tooltip/TooltipView.js#L112))
```js
tooltipContent.update(tooltipModel);
```
Pass the parameter `tooltipModel` to `update` function.
```js
var alwaysShowContent = tooltipModel.get('alwaysShowContent');
alwaysShowContent && this._moveTooltip();
```

**Comment by plainheart** [comment]
Finally, the same changed should be applied to `TooltipRichContent`, which will be used when [`renderMode`](https://echarts.apache.org/en/option.html#tooltip.renderMode) is `richText`.

File: src/component/tooltip/TooltipContent.js (hunk 7 above)
Comment (liulinboyi) [reply src/component/tooltip/TooltipContent.js:256]: > Maybe should add a judgement about whether `alwaysShowContent` is `true`
> `TooltipView.js`([Line 112](https://github.com/apache/incubator-echarts/blob/master/src/component/tooltip/TooltipView.js#L112))
> 
> ```js
> tooltipContent.update(tooltipModel);
> ```
> 
> Pass the parameter `tooltipModel` to `update` function.
> 
> ```js
> var alwaysShowContent = tooltipModel.get('alwaysShowContent');
> alwaysShowContent && this._moveTooltip();
> ```

ok i see. thank you!

**Comment by liulinboyi** [comment]
> Finally, the same changes should be applied to `TooltipRichContent`, which will be used when [`renderMode`](https://echarts.apache.org/en/option.html#tooltip.renderMode) is `richText`.

@plainheart All the problems are solved, Please help review, thanks!

File: src/component/tooltip/TooltipRichContent.js [hunk 8]
```diff
@@ -21,13 +21,34 @@ import * as zrUtil from 'zrender/src/core/util';
...
+    out[0] = zrX;
+    out[1] = zrY;
+    // xy should be based on canvas root. But tooltipContent is
+    // the sibling of canvas root. So padding of ec container
+    // should be considered here.
+    var viewportRootOffset = zrPainter && zrPainter.getViewportRootOffset();
+    if (viewportRootOffset) {
+        out[0] += viewportRootOffset.offsetLeft;
+        out[1] += viewportRootOffset.offsetTop;
+    }
```
Comment (plainheart) [inline src/component/tooltip/TooltipRichContent.js:36]: I think there is no need for adding this logic in rich tooltip, since rich tooltip won't depend on DOM.
This may bring a unexpected result which has a big space if add it here.
For example:
image

If we remove this logic, it looks like normal.
image

Comment (liulinboyi) [reply src/component/tooltip/TooltipRichContent.js:36]: > I think there is no need for adding this logic in rich tooltip, since rich tooltip won't depend on DOM.
> This may bring a unexpected result which has a big space if add it here.
> For example:
> image
> 
> If we remove this logic, it looks like normal.
> image

ok i will remove these code.

Comment (liulinboyi) [reply src/component/tooltip/TooltipRichContent.js]: > I think there is no need for adding this logic in rich tooltip, since rich tooltip won't depend on DOM.
> This may bring a unexpected result which has a big space if add it here.
> For example:
> image
> 
> If we remove this logic, it looks like normal.
> image

@plainheart All the problems are solved, Please help review, thanks!

**Comment by liulinboyi** [comment]
> Finally, the same changes should be applied to `TooltipRichContent`, which will be used when [`renderMode`](https://echarts.apache.org/en/option.html#tooltip.renderMode) is `richText`.

@plainheart Thank you for your guidance.

**Comment by plainheart** [comment]
@liulinboyi Thank you, great work! All looks good to me now, please @pissang have a look.

**Comment by plainheart** [comment]
@liulinboyi Would you mind providing a test case for this?

**Comment by liulinboyi** [comment]
> @liulinboyi Would you mind providing a test case for this?

Let me have a try.

**Comment by liulinboyi** [comment]
> @liulinboyi Would you mind providing a test case for this?

@plainheart Test case is done, Please help review, thanks!

**Comment by pissang** [comment]
Looks good to me. Thanks for the wonderful work! @liulinboyi @plainheart

**Comment by liulinboyi** [comment]
> Perhaps the `_moveTooltip` can be renamed to a more specific name like `_moveTooltipIfResized`
> 
> Others all look good to me. Thanks for the wonderful work! @liulinboyi @plainheart

Ok, no problem.

**Comment by liulinboyi** [comment]
> Perhaps the `_moveTooltip` can be renamed to a more specific name like `_moveTooltipIfResized`
> 
> Others all look good to me. Thanks for the wonderful work! @liulinboyi @plainheart

Thank you for your guidance. @pissang I have fix some spell error and the _moveTooltip  was renamed, Please help review, thanks!

**Comment by pissang** [comment]
Seems there are still two request changes from @plainheart @susiwen8  need to be resolved before this PR can ben merged

**Comment by liulinboyi** [comment]
> Seems there are still two request changes from @plainheart @susiwen8 need to be resolved before this PR can ben merged

@pissang  All request changes are done. Can i fix other files spell error?

File: test/tooltip-windowResize.html [hunk 9]
```diff
@@ -0,0 +1,383 @@
...
+                ]
+            };
+
+            var chart = testHelper.create(echarts, 'main1', {
+                option: option
+            });
+            chart.setOption(option, true);
+            window.onresize = function () {
+                chart.resize();
+            }
```
Comment (plainheart) [inline test/tooltip-windowResize.html:377]: Consider using `window.addEventListener`, `window` is shard with these two test cases, `window.onresize` in the bottom test case will override the top one.

File: src/component/tooltip/TooltipContent.js [hunk 10]
```diff
@@ -250,11 +252,25 @@ TooltipContent.prototype = {
...
+        alwaysShowContent && this._moveTooltipIfResized();
         // Hide the tooltip
         // PENDING
         // this.hide();
     },
 
+    /**
+     * when alwaysShowContent is true change or rotation window size and restore will move tooltip
+     * @private
+     */
```
Comment (plainheart) [inline src/component/tooltip/TooltipContent.js:265]: Here is a suggestion for this comment
```js
// when `alwaysShowContent` is true,
// we should move the tooltip after chart resized
```

File: test/tooltip-windowResize.html (hunk 9 above)
Comment (liulinboyi) [reply test/tooltip-windowResize.html:377]: > Consider using `window.addEventListener`, `window` is shard with these two test cases, `window.onresize` in the bottom test case will override the top one.

ok, i see, thank you!

File: src/component/tooltip/TooltipContent.js (hunk 10 above)
Comment (liulinboyi) [reply src/component/tooltip/TooltipContent.js:265]: > Here is a suggestion for this comment
> 
> ```js
> // when `alwaysShowContent` is true,
> // we should move the tooltip after chart resized
> ```

ok, i see, thank you!

**Comment by plainheart** [comment]
> > Seems there are still two request changes from @plainheart @susiwen8 need to be resolved before this PR can ben merged
> 
> @pissang All request changes are done. Can i fix other files spell error?

Merged. Thanks for your contribution! 
And for the request to fix spell error, I think you are welcome and free to do it.
