### PR TITLE
Fix(tooltip.textStyle): fix color not working

### LINKED ISSUE #13797: 5.0 pie下 tooltip 的textStyle.color 设置无效
### Version
5.0.0

### Steps to reproduce
5.0 pie下 tooltip 的textStyle.color 设置无效，官方网站中的试一试也无效。

Chrome 86.0.4240.111
OS: deepin 20.1Beta

### What is expected?
What is expected?

### What is actually happening?
What is actually happening?

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fix tooltip.textStyle.color not working

### Fixed issues

Close #13797 

### Before: What was the problem?
Screen Shot 2020-12-20 at 17 20 15

### After: How is it fixed in this PR?
Screen Shot 2020-12-20 at 17 20 52

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### Other information
`tooltip name` and `value` can be configured separately. More textStyle support

### CODE REVIEW

File: src/component/tooltip/tooltipMarkup.ts [hunk 1]
```diff
@@ -32,20 +32,66 @@ import { getRandomIdBase } from '../../util/number';
...
+): {
+    nameStyle: TextStyle
+    valueStyle: TextStyle
+} {
+    const nameFontColor = textStyle.color || '#6e7079';
+    const nameFontSize = textStyle.fontSize || '12px';
+    const valueFontColor = textStyle.color || '#464646';
+    const valueFontSize = textStyle.fontSize || '14px';
+    const valueFontWeight = textStyle.fontWeight || '900';
+    // const fontStyle = textStyleModel.get('fontStyle');
```
Comment (pissang) [inline src/component/tooltip/tooltipMarkup.ts:59]: Unused code is better to be removed instead of commented.

Comment (susiwen8) [reply src/component/tooltip/tooltipMarkup.ts]: @pissang useless code has been removed

File: src/component/tooltip/tooltipMarkup.ts [hunk 2]
```diff
@@ -401,36 +446,46 @@ function wrapBlockHTML(
...
 function wrapInlineValueRichText(
     ctx: TooltipMarkupBuildContext,
     valueList: string[],
     alignRight: boolean,
-    valueCloseToMarker: boolean
+    valueCloseToMarker: boolean,
+    style: RichTextStyle
 ): string {
-    const styles: Dictionary<unknown>[] = [TOOLTIP_VALUE_TEXT_STYLE_RICH];
+    const styles: Dictionary<unknown>[] = [style];
```
Comment (chfw) [inline src/component/tooltip/tooltipMarkup.ts:488]: Instead of unknown, use `RichTextStyle`? i.e.:

const styles: Dictionary<RichTextStyle>[] = [style];

File: src/component/tooltip/tooltipMarkup.ts [hunk 3]
```diff
@@ -278,20 +318,22 @@ const builderMap: { [key in TooltipMarkupBlockFragment['type']]: TooltipMarkupFr
...
                 : wrapBlockHTML(
                     (noMarker ? '' : markerStr)
-                    + (noName ? '' : wrapInlineNameHTML(readableName, !noMarker))
+                    + (noName ? '' : wrapInlineNameHTML(readableName, !noMarker, nameStyle as string))
                     + (noValue ? '' : wrapInlineValueHTML(
-                        readableValueList, valueAlignRight, valueCloseToMarker
+                        readableValueList, valueAlignRight, valueCloseToMarker, valueStyle as string
                     )),
                     topMarginForOuterGap
                 );
```
Comment (chfw) [inline src/component/tooltip/tooltipMarkup.ts:339]: I think here is an abuse of short hand if-else statement. It is inviting bugs to live inside and adds difficulty in debugging it.

**Review by nelsonbbarriento23 — DISMISSED** [review]

File: src/component/tooltip/tooltipMarkup.ts [hunk 4]
```diff
@@ -32,20 +32,52 @@ import { getRandomIdBase } from '../../util/number';
...
+
+type TextStyle = string | RichTextStyle;
+
 const TOOLTIP_LINE_HEIGHT_CSS = 'line-height:1';
 
+// TODO: more textStyle option
+function getTooltipTextStyle(
+    textStyle: TooltipOption['textStyle'],
+    renderMode: TooltipRenderMode,
+    tooltipModel?: Model<TooltipOption>
```
Comment (pissang) [inline src/component/tooltip/tooltipMarkup.ts:49]: Parameter `tooltipModel` is not used here.

File: src/component/tooltip/tooltipMarkup.ts [hunk 5]
```diff
@@ -32,20 +32,52 @@ import { getRandomIdBase } from '../../util/number';
...
+): {
+    nameStyle: TextStyle
+    valueStyle: TextStyle
+} {
+    const nameFontColor = textStyle.color || '#6e7079';
+    const nameFontSize = textStyle.fontSize || '12px';
+    const valueFontColor = textStyle.color || '#464646';
+    const valueFontSize = textStyle.fontSize || '14px';
+    const valueFontWeight = textStyle.fontWeight || '900';
```
Comment (pissang) [inline src/component/tooltip/tooltipMarkup.ts:58]: It's a bit confusing that only `value` text can change the font-weight. I will prefer both `name` and `value` will be set, just like `fontSize` and `fill`

In the long term, we can discuss a new set of options that can configure each part of the tooltip with enough flexibility. For example the style and formatter of each value.  Of cause that should be a new topic and can be designed in a new pull request.

File: src/component/tooltip/tooltipMarkup.ts (hunk 2 above)
Comment (pissang) [reply src/component/tooltip/tooltipMarkup.ts:488]: @chfw  I noticed @100pah is using `Dictionary<unknown>` to represent the style object in this module. I think it's mainly because the style can be both RichTextStyle or normal CSS style for HTML Text.

**Comment by pissang** [comment]
Sorry for the late review. I left my comments about some tiny change suggestions. Other changes look good to me. @100pah can have a double check.

File: src/component/tooltip/tooltipMarkup.ts (hunk 2 above)
Comment (100pah) [reply src/component/tooltip/tooltipMarkup.ts:488]: In fact, the accurate type of `ctx.markupStyleCreator.richTextStyles` should be `Dictionary<TextStylePropsPart>`, which is the same as `textStyle.rich`.

**Review by 100pah — CHANGES_REQUESTED** [review]

File: src/component/tooltip/tooltipMarkup.ts [hunk 6]
```diff
@@ -32,20 +32,52 @@ import { getRandomIdBase } from '../../util/number';
...
+function getTooltipTextStyle(
+    textStyle: TooltipOption['textStyle'],
+    renderMode: TooltipRenderMode,
+    tooltipModel?: Model<TooltipOption>
+): {
+    nameStyle: TextStyle
+    valueStyle: TextStyle
+} {
+    const nameFontColor = textStyle.color || '#6e7079';
+    const nameFontSize = textStyle.fontSize || '12px';
```
[the remark this answers is not in the document]
Comment (susiwen8) [reply src/component/tooltip/tooltipMarkup.ts:55]: I don't get it. If `fontSize` default value were `12`, then it would become `font-size:12`, which is not the correct format.

[the remark this answers is not in the document]
Comment (100pah) [reply src/component/tooltip/tooltipMarkup.ts:54]: @susiwen8 
I means that user will set `fontSize` in option like
```js
tooltip: {
    textStyle: { fontSize: 14 }
}
```
And then `textStyle.fontSize` has the value `14` rather than `14px` here.
And then the html template should be like:
```js
return {
    nameStyle: `font-size:${nameFontSize}px;color:${nameFontColor};font-weight:${nameFontWeight}`,
    valueStyle: `font-size:${valueFontSize}px;color:${valueFontColor};font-weight:${valueFontWeight}`
}
```
If we intend to support other unit like `em`/`rem`/... in future, it would be another topic, and could be discussed in new thread.

**Review by 100pah — CHANGES_REQUESTED** [review]

**Comment by susiwen8** [comment]
@100pah @100pah Hi, I have correct my code, please review it again, thanks

**Comment by pissang** [comment]
LGTM now:)

**Review by 100pah — APPROVED** [review]
